### ISSUE TITLE
UI suggestion: Synopsis labeled in parallel with other data

### ISSUE THREAD

**Issue by chrisaldrich** [donnapep/book-review#24]
Given the way the standard data in "book info" (except the star rating) is scrapped based on ISBN, it would be nice if the word "Synopsis" appeared in bold in front of the synopsis to provide a similar parallelism between it and the book title, author, etc.

This tweak to the UI would help to indicate a more parallel structure for the base book data and help to separate it from the user's actual review. Without it, some readers of reviews may mistakenly assume the reviewer wrote the text rather than it more likely being scraped from the publisher's description.

Similarly it might make better UI to have the star rating separated from the rest or possibly preceded by "My rating" (in bold) to indicate it as separate from the rest of the bulk data as well? Perhaps adding fields for other User specific data like "date started" and "date completed" would aid in this separation from basic book data and user generated data.

**Comment by donnapep** [comment]
This plugin has been deprecated and is replaced by [Book Review Block](https://wordpress.org/plugins/book-review-block).
